from .nodes import (
    SamplerGeneratorNode,
    SchedulerGeneratorNode,
    ModelGeneratorNode,
    DiffusionModelGeneratorNode,
    AnyAdapterNode,
    CheckpointSelectorNode,
    DiffusionModelSelectorNode,
    VAEGeneratorNode,
    TextEncoderGeneratorNode,
    VAESelectorNode,        
    TextEncoderSelectorNode,
    StringToIntNode,          
    StringToFloatNode,
    TextConcatNode,
    LORASelectorNode,
    ClipSkipSliderNode,
    PonyPrefixesNode,
    ImageResizeNode,
)

NODE_CLASS_MAPPINGS = {
    "SamplerGeneratorNode": SamplerGeneratorNode,
    "SchedulerGeneratorNode": SchedulerGeneratorNode,
    "ModelGeneratorNode": ModelGeneratorNode,
    "DiffusionModelGeneratorNode": DiffusionModelGeneratorNode,
    "AnyAdapterNode": AnyAdapterNode,
    "CheckpointSelectorNode": CheckpointSelectorNode,
    "DiffusionModelSelectorNode": DiffusionModelSelectorNode,
    "VAEGeneratorNode": VAEGeneratorNode, 
    "TextEncoderGeneratorNode": TextEncoderGeneratorNode,
    "VAESelectorNode": VAESelectorNode,
    "TextEncoderSelectorNode": TextEncoderSelectorNode,
    "StringToIntNode": StringToIntNode,
    "StringToFloatNode": StringToFloatNode,
    "TextConcatNode": TextConcatNode,
    "LORASelectorNode": LORASelectorNode,
    "ClipSkipSliderNode": ClipSkipSliderNode,
    "PonyPrefixesNode": PonyPrefixesNode,
    "ImageResizeNode": ImageResizeNode,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "SamplerGeneratorNode": "Dynamic Sampler Selector",
    "SchedulerGeneratorNode": "Dynamic Scheduler Selector",
    "ModelGeneratorNode": "Dynamic Checkpoint Selector",
    "DiffusionModelGeneratorNode": "Dynamic Diffusion Model Selector",
    "AnyAdapterNode": "Any‑to‑Any Adapter",
    "СheckpointSelectorNode": "Checkpoint Selector",
    "DiffusionModelSelectorNode": "Diffusion Model Selector",
    "VAEGeneratorNode": "Dynamic VAE Selector",
    "TextEncoderGeneratorNode": "Dynamic Encoder Selector",
    "VAESelectorNode": "Dynamic VAE Selector",
    "TextEncoderSelectorNode": "Dynamic Encoder Selector",
     "StringToIntNode": "String to Integer",
    "StringToFloatNode": "String to Float",
    "TextConcatNode": "Text Concatenator",
    "LORASelectorNode": "Dynamic LORA Selector",
    "ClipSkipSliderNode": "Clip Skip Slider",
    "PonyPrefixesNode": "Rating, Score, Source for Pony",
    "ImageResizeNode": "Image Resize",
}
